version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: aqif
      POSTGRES_PASSWORD: p
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this is the correct Dockerfile name
    environment:
      DATABASE_URL: postgresql+asyncpg://aqif:p@db:5432/fastapi
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  alembic:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this is the correct Dockerfile name
    environment:
      DATABASE_URL: postgresql+asyncpg://aqif:p@db:5432/fastapi
    command: alembic upgrade head
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:



